=== SMART LIBRARY MANAGEMENT & RECOMMENDATION SYSTEM ===

1. TAMBAH HUBUNGAN PINJAM
2. REKOMENDASI
3. KELUAR

Pilih: 1
ISBN Buku 1: ISBN-0001
ISBN Buku 2: ISBN-0002

Relasi pola peminjaman berhasil ditambahkan.

=== SMART LIBRARY MANAGEMENT & RECOMMENDATION SYSTEM ===

1. TAMBAH HUBUNGAN PINJAM
2. REKOMENDASI
3. KELUAR

Pilih: 1
ISBN Buku 1: ISBN-0001
ISBN Buku 2: ISBN-0002

Relasi pola peminjaman berhasil ditambahkan.

=== SMART LIBRARY MANAGEMENT & RECOMMENDATION SYSTEM ===

1. TAMBAH HUBUNGAN PINJAM
2. REKOMENDASI
3. KELUAR

Pilih: 2
ISBN Buku : ISBN-0001

=== SISTEM REKOMENDASI PINTAR ===
1. ISBN-0002 (Skor: 2)

Big-O Graph BFS = O(V + E)

=== SMART LIBRARY MANAGEMENT & RECOMMENDATION SYSTEM ===

1. TAMBAH HUBUNGAN PINJAM
2. REKOMENDASI
3. KELUAR

Pilih: 3

Program selesai.
